_wandb:
    value:
        cli_version: 0.24.2
        e:
            95kg1e3ynch824kogwmrcheu7af2nzju:
                codePath: LLM_Finetune_vLLM.ipynb
                codePathLocal: LLM_Finetune_vLLM.ipynb
                cpu_count: 20
                cpu_count_logical: 20
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "4030802149376"
                        used: "1073427423232"
                email: jungseonglian@sju.ac.kr
                executable: /home/vsc/LLM_TUNE/.venv_vLLM/bin/python
                git:
                    commit: e0f43d0b97f98a1bd52a034c2aec670514a322aa
                    remote: https://github.com/JungSeong/QA-FineTune.git
                gpu: NVIDIA GB10
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 6144
                      name: NVIDIA GB10
                      uuid: GPU-60537a4e-7dee-602c-d7e8-248b8e3da4fe
                host: edgexpert-a167
                memory:
                    total: "128522862592"
                os: Linux-6.14.0-1015-nvidia-aarch64-with-glibc2.39
                program: LLM_Finetune_vLLM.ipynb
                python: CPython 3.12.3
                root: /home/vsc/LLM_TUNE/도서관_QA_Finetune
                startedAt: "2026-02-08T15:07:34.820369Z"
                writerId: 95kg1e3ynch824kogwmrcheu7af2nzju
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 95
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 95
            "3":
                - 13
            "4": 3.12.3
            "5": 0.24.2
            "6": 5.0.0
            "8":
                - 1
            "12": 0.24.2
            "13": linux-aarch64
