_wandb:
    value:
        cli_version: 0.24.2
        e:
            s6wmk8e8u8yrrh624x2hdc2ma9qxapxu:
                codePath: 도서관_QA_Finetune/LLM_Finetune_vLLM.ipynb
                cpu_count: 20
                cpu_count_logical: 20
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "4030802149376"
                        used: "1072940900352"
                email: jungseonglian@sju.ac.kr
                executable: /home/vsc/LLM_TUNE/.venv_vLLM/bin/python
                git:
                    commit: 13352d5759f5c114046b1dfb15dfb879dc9c71d3
                    remote: https://github.com/JungSeong/Library-QA-FineTune.git
                gpu: NVIDIA GB10
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 6144
                      name: NVIDIA GB10
                      uuid: GPU-60537a4e-7dee-602c-d7e8-248b8e3da4fe
                host: edgexpert-a167
                memory:
                    total: "128522854400"
                os: Linux-6.14.0-1015-nvidia-aarch64-with-glibc2.39
                program: 도서관_QA_Finetune/LLM_Finetune_vLLM.ipynb
                python: CPython 3.12.3
                root: /home/vsc/LLM_TUNE/도서관_QA_Finetune
                startedAt: "2026-02-08T08:50:32.091850Z"
                writerId: s6wmk8e8u8yrrh624x2hdc2ma9qxapxu
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 95
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 95
            "3":
                - 13
            "4": 3.12.3
            "5": 0.24.2
            "6": 5.0.0
            "8":
                - 1
            "12": 0.24.2
            "13": linux-aarch64
